language: python
os:
  - linux
  - osx
python:
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
before_install:
  - "sudo (ln -s /usr/share/i18n/SUPPORTED /var/lib/locales/supported.d/all;locale-gen)"
install:
  - "pip install -r requirements.txt"
  - "sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-xetex"
script:
  - "snakemake -s Snakefile.AllSongs"
  - "snakemake -s Snakefile.TP2011"
  - "snakemake -s Snakefile.TP2012"
  - "snakemake -s Snakefile.TP2013"
  
